# Generated by Django 3.2 on 2022-06-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='titl',
            new_name='name',
        ),
    ]
