# Generated by Django 3.2 on 2022-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_titl_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='d', upload_to=''),
            preserve_default=False,
        ),
    ]
