# Generated by Django 3.2 on 2022-06-12 16:45

from django.db import migrations, models
import student.utils


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.utils.upload_image_path),
        ),
    ]
